version: "3.9"
services:
  streamlit:
    build: ./docker/streamlit
    command: streamlit run ./app/main.py --server.port 8501
    volumes:
        - ./:/usr/src/app
    ports:
        - 8501:8501
    image: yourstreamlitapp:latest
  jupyter:
    build: ./docker/jupyter
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
